[project]
name = "projeto-nyc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-cloud-storage>=3.7.0",
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
]
